#if !canImport(ObjectiveC)
import XCTest

extension InterplateTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InterplateTests = [
        ("testDefault", testDefault),
        ("testExtension", testExtension),
        ("testHelloWorld", testHelloWorld),
        ("testInclude", testInclude),
        ("testIndent", testIndent),
        ("testLoop", testLoop),
        ("testTrim", testTrim),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InterplateTests.__allTests__InterplateTests),
    ]
}
#endif
